version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks: 
      - db_network       
    volumes:
      - pg_data:/var/lib/postgresql/data/
  pg_admin:
    container_name: pg_admin_ui
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a 
    ports:
      - "5050:80"
    depends_on:
      - db  
    volumes:
      - admin:/var/lib/pgadmin
    networks: 
      - db_network  
    tty: true    
volumes:
  pg_data:
  admin:
networks:
  db_network:
    driver: bridge